bipsu_online_exam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('users/', include('users.urls'))
]

main_app/urls.py
from django.urls import path

from . import views as users_views

app_name = "main"
urlpatterns = [
    path('', users_views.home, name="home"),
    path('add_exam/', users_views.add_exam, name='add_exam'),
    path('all_exams/', users_views.all_exams, name='all_exams'),
    path('delete_exam/<int:exam_id>/', users_views.delete_exam, name='delete_exam'),

    path('manage_exam/<int:exam_id>/add_question/', users_views.add_question, name='add_question'),
    path('manage_exam/<int:exam_id>/edit_exam/', users_views.edit_exam, name='edit_exam'),
    path('manage_exam/<int:exam_id>/show_exam/', users_views.show_exam, name='show_exam'),
    path('manage_exam/<int:exam_id>/do_edit_exam/', users_views.do_edit_exam, name='do_edit_exam'),

    path('manage_exam/<int:exam_id>/manage_questions/', users_views.manage_questions, name='manage_questions'),

    path('do_exam/<int:exam_id>/', users_views.do_exam, name='do_exam'),
    path('update_question/<int:exam_id>/<int:question_id>/', users_views.update_question, name='update_question'),
    path('delete_question/<int:exam_id>/<int:question_id>/', users_views.delete_question, name='delete_question'),
    path('delete_exam/<int:exam_id>/', users_views.delete_exam, name='delete_exam'),
    path('submit_exam/', users_views.submit_exam, name='submit_exam'),
    path('students_scores/', users_views.students_scores, name='students_scores'),

    path('clear_scores/', users_views.clear_scores, name='clear_scores'),

    path('publish_exam/<int:exam_id>/', users_views.publish_exam, name='publish_exam'),
    path('un_publish_exam/<int:exam_id>/', users_views.un_publish_exam, name='un_publish_exam')
]

users/urls.py
from django.urls import path
from . import views as users_views


app_name = "users"
urlpatterns = [

    path('', users_views.home, name='home'),

    path('examiners/sign_up/', users_views.examiner_sign_up, name='examiner_sign_up'),
    path('students/sign_up/', users_views.student_sign_up, name='student_sign_up'),

    path('login/', users_views.the_login, name='login'),

    path('logout/', users_views.the_logout, name='logout'),

    # path('examiners/logout/', users_views.examiner_logout, name='examiner_logout'),
    # path('students/logout/', users_views.student_logout, name='student_logout'),

    path('examiners/<slug>/', users_views.examiner_profile, name='examiner_profile'),
    path('students/<slug>/', users_views.student_profile, name='student_profile'),

]

main_app/models.py
from django.db import models
from django.utils.text import slugify
from users.models import MyUser
from django.utils import timezone


class Exam(models.Model):
    examiner = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='exams')
    exam_name = models.CharField(max_length=255)
    slug = models.SlugField(null=True, blank=True)
    category = models.CharField(max_length=255)
    exam_creation_date = models.DateTimeField(default=timezone.datetime.now())
    is_published = models.BooleanField(default=False)
    students = models.ManyToManyField(MyUser, related_name='+')
    num_of_questions = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.exam_name)
        super(Exam, self).save(*args, **kwargs)

    def __str__(self):
        return self.slug


class Question(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    body = models.TextField(max_length=4096)
    op1 = models.CharField(max_length=255)
    op2 = models.CharField(max_length=255)
    op3 = models.CharField(max_length=255)
    op4 = models.CharField(max_length=255)
    correct_ans = models.IntegerField()

    def __str__(self):
        return str(self.body)


# Mapping many-to-many relationship attributes

class TakenExam(models.Model):
    student = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    score = models.IntegerField()
    full_mark = models.IntegerField()
    done_date = models.DateTimeField(default=timezone.datetime.now())

    def __str__(self):
        return self.student.user.username + '\'s score in ' + self.exam.exam_name + ' exam'

main_app/forms.py
from django import forms
from .models import Exam


class AddExamForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = ['exam_name', 'category']


class EditExamForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = ['exam_name', 'category']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt

from .forms import AddExamForm, EditExamForm
from .models import Exam, Question, TakenExam
from users.models import MyUser
from django.shortcuts import get_object_or_404
from django.contrib import messages


def home(request):
    return render(request, 'main_app/home.html')


def add_exam(request):

    if request.method == 'POST':
        form = AddExamForm(request.POST)

        if form.is_valid():
            exam_name = form.cleaned_data.get('exam_name')
            category = form.cleaned_data.get('category')

            # check if found exam with same name and category
            temp = Exam.objects.filter(
                exam_name__iexact=exam_name,
                category__iexact=category
            )

            if temp:
                messages.error(request, "Found exam with same name and category")
                return redirect('main:add_exam')

            else:
                Exam.objects.get_or_create(examiner=request.user.myuser, exam_name=exam_name, category=category)
                messages.success(request, f"( {exam_name} exam ) added successfully")
                return redirect('main:all_exams')

    else:
        form = AddExamForm()

    data = {
        'form': form
    }
    return render(request, 'main_app/add_exam.html', data)


def all_exams(request):

    exams = Exam.objects.filter(examiner=request.user.myuser)
    for exam in exams:
        n = Question.objects.filter(exam=exam)
        exam.num_of_questions = len(n)

    data = {
        'exams': exams,
        'current_user': request.user.myuser,
        'exams_count': range(len(exams))
    }
    return render(request, 'main_app/all_exams.html', data)


def delete_exam(request, exam_id):
    exam_to_delete = ""
    if request.method == 'POST':
        exam = get_object_or_404(Exam, id=exam_id)
        exam_to_delete = exam.exam_name
        exam.delete()

    messages.success(request, f" ( {exam_to_delete} Exam ) deleted successfully")
    return redirect('main:all_exams')


def add_question(request, exam_id):
    if request.method == 'POST':

        exam = Exam.objects.get(id=exam_id)

        q_body = request.POST.get('newQ_body')
        op1 = request.POST.get('newQ_option1')
        op2 = request.POST.get('newQ_option2')
        op3 = request.POST.get('newQ_option3')
        op4 = request.POST.get('newQ_option4')
        correct_ans = request.POST.get('newQ_correctA')

        Question.objects.get_or_create(exam=exam,
                                       body=q_body,
                                       op1=op1,
                                       op2=op2,
                                       op3=op3,
                                       op4=op4,
                                       correct_ans=correct_ans)
        messages.success(request, "Question added successfully")
        return HttpResponse(1)

    else:
        return HttpResponse(0)


def edit_exam(request, exam_id):

    form = EditExamForm()

    exam = Exam.objects.get(id=exam_id)

    form.initial['exam_name'] = exam.exam_name
    form.initial['category'] = exam.category

    data = {
        'form': form,
        'exam_id': exam_id,
    }

    return render(request, 'main_app/edit_exam.html', data)


def do_edit_exam(request, exam_id):

    if request.method == 'POST':
        exam = Exam.objects.get(id=exam_id)

        name = request.POST.get('exam_name')
        category = request.POST.get('category')

        # if nothing is changed
        if exam.exam_name == name and exam.category == category:
            return redirect("main:all_exams")

        # check if found exam with same name and category
        exams = Exam.objects.filter(examiner=request.user.myuser).exclude(id=exam_id)
        temp = exams.filter(exam_name__iexact=name, category__iexact=category)

        if temp:
            messages.error(request, "Found exam with same name and category")
            return redirect("main:edit_exam", exam_id)

        else:
            exam.exam_name = name
            exam.category = category
            exam.save()

            messages.success(request, "The exam updated successfully")
            return redirect("main:all_exams")


def manage_questions(request, exam_id):

    exam = Exam.objects.get(id=exam_id)
    exam_name = exam.exam_name
    exam_category = exam.category

    questions = Question.objects.filter(exam=exam)

    data = {
        'exam_id': exam_id,
        'exam_name': exam_name,
        'exam_category': exam_category,
        'questions': questions
    }
    return render(request, 'main_app/manage_questions.html', data)


def show_exam(request, exam_id):
    exam = Exam.objects.get(id=exam_id)
    exam_name = exam.exam_name
    exam_category = exam.category

    questions = Question.objects.filter(exam=exam)
    questions_count = len(questions)

    data = {
        'exam_id': exam_id,
        'exam_name': exam_name,
        'exam_category': exam_category,
        'questions': questions,
        'questions_count': questions_count
    }

    return render(request, 'main_app/show_exam.html', data)


def do_exam(request, exam_id):

    if request.method == 'POST':
        exam = Exam.objects.get(id=exam_id)
        exam_name = exam.exam_name
        exam_category = exam.category

        # check if the student take this exam before or not
        temp = TakenExam.objects.filter(exam=exam, student=request.user.myuser)

        if temp:
            messages.error(request, f"You have done this exam before !")
            return redirect("users:home")

        else:
            questions = Question.objects.filter(exam=exam)
            questions_count = len(questions)

        data = {
            'exam_id': exam_id,
            'std_id': request.user.id,
            'exam_name': exam_name,
            'exam_category': exam_category,
            'questions': questions,
            'questions_count': questions_count
        }

        return render(request, 'main_app/do_exam.html', data)


def update_question(request, exam_id, question_id):
    if request.method == 'POST':

        question = Question.objects.get(id=question_id)

        q_body = request.POST.get('qBody')
        op1 = request.POST.get('op1')
        op2 = request.POST.get('op2')
        op3 = request.POST.get('op3')
        op4 = request.POST.get('op4')
        correct_ans = request.POST.get('correctA')

        question.body = q_body
        question.op1 = op1
        question.op2 = op2
        question.op3 = op3
        question.op4 = op4
        question.correct_ans = correct_ans

        question.save()
        messages.success(request, "Question updated successfully")

        return HttpResponse(1)
        # return redirect('main:manage_questions', exam_id)

    else:
        return HttpResponse(0)


def delete_question(request, exam_id, question_id):

    question = get_object_or_404(Question, id=question_id)
    question.delete()

    messages.success(request, 'Question deleted successfully')
    return redirect('main:manage_questions', exam_id)


def delete_exam(request, exam_id):

    exam = get_object_or_404(Exam, id=exam_id)
    exam.delete()

    messages.success(request, 'Exam deleted successfully')
    return redirect('main:all_exams')


def submit_exam(request):
    if request.method == 'POST':

        exam_id = request.POST.get('examID')
        std_id = request.POST.get('stdID')
        answers = request.POST.get('answers')
        # !!!!! really strange : if I write : -> request.POST['answers'] : produces Internal Server Error (500)

        # get the exam questions to calc scores
        all_questions = Question.objects.filter(exam=exam_id)

        # to make the answers iterable, because now it's one string, so we want to remove the commas
        answers = answers.split(',')

        # calc student score in the exam
        score = 0
        for i in range(len(answers)):
            if int(answers[i]) == int(all_questions[i].correct_ans):
                score += 1

        # get the exam and the student and add the score in the database
        exam = Exam.objects.get(id=exam_id)
        student = request.user.myuser

        TakenExam.objects.get_or_create(student=student, exam=exam, score=score, full_mark=len(all_questions))
        return HttpResponse(1)
    else:
        return HttpResponse(0)


def students_scores(request):

    temp = TakenExam.objects.all()
    results = []
    for t in temp:
        if t.exam.examiner == request.user.myuser:
            results.append(t)

    data = {
        'results': results
    }
    return render(request, 'main_app/students_scores.html', data)


def clear_scores(request):

    # get all the exams that created by this examiner
    exams_to_delete = Exam.objects.filter(examiner=request.user.myuser)

    # delete all scores that related to those exams (clear operation)
    for x in exams_to_delete:
        x.takenexam_set.all().delete()

    '''
        # The NONE efficient way to do (clear operation)
        
        # targeted_exams = Exam.objects.filter(examiner=request.user.myuser)
        # temp = TakenExam.objects.filter(exam=targeted_exams).delete()
        #
        # for t in temp:
        #     if t.exam.examiner == request.user.myuser:
        #         t.delete()
    '''

    messages.success(request, "All scores cleared successfully")
    return redirect("users:home")


def publish_exam(request, exam_id):

    exam = get_object_or_404(Exam, id=exam_id)
    exam.is_published = True
    exam.save()

    messages.success(request, 'Exam published successfully')
    return redirect('main:all_exams')


def un_publish_exam(request, exam_id):

    exam = get_object_or_404(Exam, id=exam_id)
    exam.is_published = False
    exam.save()

    messages.success(request, 'Exam Un-published successfully')

main_app/templates/main_app/add_exam.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
    <title>Add Exam</title>
{% endblock %}


{% block custom_css %}
    <link rel="stylesheet" href="{% static 'main_app/css/add_exam.css' %}">
{% endblock %}

{% block logout_in_navbar %}

    {% include 'sign_out_button.html' %}

{% endblock %}


{% block content %}

    <div class="container" style="padding: 10px;">

        <h1 class="display-4">Add Exam</h1>

        <div class="my_container">
                <form method="post" action="{% url 'main:add_exam' %}">{% csrf_token %}
                    {{ form|crispy }}
                    <span><a href="{% url 'users:home' %}" id="backbtn" class="btn btn-secondary backBtn">Back</a></span>
                    <button type="submit" class="btn btn-success">Add <i class="fa fa-plus"></i></button>
                </form>
        </div>
    </div>


{% endblock %}

main_app/templates/main_app/all_exams.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block title %}
    <title>All Exams</title>
{% endblock %}


{% block custom_css %}
    <link rel="stylesheet" href="{% static 'main_app/css/all_exams.css' %}">
{% endblock %}

{% block logout_in_navbar %}

    {% include 'sign_out_button.html' %}

{% endblock %}


{% block content %}

    <div class="container">
        <div class="row">
            <div class="col">

                <div class="display-4">All Exams</div>

                <div class="table-responsive">
                    <table class="table">
                        {% if exams %}
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Exam Name</th>
                                <th>Category</th>
                                <th>Questions</th>
                                <th>Actions</th>
                                <th>Published</th>
                            </tr>
                        </thead>

                        <tbody id="table_body">

                            {% for exam in exams %}
                            <tr>
                                <td class="examsCounter">{{ forloop.counter }}</td>
                                <td>{{ exam.exam_name }}</td>
                                <td>{{ exam.category }}</td>
                                <td>{{ exam.num_of_questions }}</td>
                                <td>

                                    <form style="display: inline" method="post" action="{% url 'main:show_exam' exam.id %}">{% csrf_token %}
<!--                                        <input type="submit" class="btn btn-outline-primary" value="Show">-->
                                        <button type="submit" class="btn btn-outline-primary">Show <i class="fa fa-eye"></i></button>
                                    </form>

                                    <form style="display: inline" method="post" action="{% url 'main:edit_exam' exam.id %}">{% csrf_token %}
<!--                                        <input type="submit" class="btn btn-outline-secondary"  value="Edit">-->
                                        <button type="submit" class="btn btn-outline-secondary">Edit <i class="far fa-edit"></i></button>
                                    </form>

                                    <form style="display: inline" method="post" action="{% url 'main:manage_questions' exam.id %}">{% csrf_token %}
<!--                                        <input type="submit" class="btn btn-outline-success"  value="Manage Questions">-->
                                        <button type="submit" class="btn btn-outline-success">Questions <i class="fa fa-cog"></i></button>
                                    </form>

<!--                                    <input type="button" onclick="delete_exam({{exam.id}}, '{{exam.exam_name}}')" class="btn btn-outline-danger" value="Delete">-->
                                    <button type="button" onclick="delete_exam({{exam.id}}, '{{exam.exam_name}}')" class="btn btn-outline-danger">Delete <i class="far fa-trash-alt"></i></button>


                                </td>
                                <td>

                                    <input id="publish_exam_{{exam.id}}" type="checkbox" onclick="publish_exam({{exam.id}}, '{{exam.exam_name}}', '{{ exam.num_of_questions }}')"
                                           {% if exam.is_published %} checked {% endif %}>

                                </td>
                            </tr>
                            {% endfor %}
                        {% else %}

                                <h4 class="noExams">No exams found</h4>

                        {% endif %}


                        </tbody>
                    </table>
                </div>

                <hr>
                <a href="{% url 'users:examiner_profile' current_user.slug %}"  class="btn btn-secondary myBtn">Back</a>
                <a class="btn btn-success" href="{% url 'main:add_exam' %}">Add Exam <i class="fa fa-plus"></i></a>
            </div>
        </div>
    </div>



{% endblock %}

{% block custom_js %}
    <script src="{% static 'main_app/js/all_exams.js' %}"></script>
{% endblock %}

main_app/templates/main_app/edit_exam.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block title %}
    <title>Edit Exam</title>
{% endblock %}


{% block custom_css %}
    <link rel="stylesheet" href="{% static 'main_app/css/edit_exam.css' %}">
{% endblock %}


{% block logout_in_navbar %}

    {% include 'sign_out_button.html' %}

{% endblock %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h2 class="display-4">Edit Exam</h2>

            <div class="my_container">

                <form method="post" action="{% url 'main:do_edit_exam' exam_id %}">{% csrf_token %}
                    {{ form.exam_name|as_crispy_field }}

                    {{ form.category|as_crispy_field }}

                    <span><a href="{% url 'main:all_exams' %}" id="backbtn" class="btn btn-secondary backBtn">Back</a></span>
                    <button type="submit" class="btn btn-success">Save <i class="far fa-save"></i></button>

                </form>

            </div>


        </div>
    </div>
</div>


{% endblock %}

main_app/templates/main_app/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Home</title>
{% endblock %}


{% block custom_css %}
    <link rel="stylesheet" href="{% static 'main_app/css/home.css' %}">
{% endblock %}


{% block content %}

    <div class="container" style="padding: 30px">
        <div class="jumbotron my_jumbotron">
          <h1 class="display-4">Welcome</h1>
          <p class="lead">Bipsu Online Exam</p>
          <hr class="my-4">
          <p><i class="fa fa-leaf"></i> - As an <b>Examiner</b> you can create, manage and publish online exams easily.</p>
          <p><i class="fa fa-leaf"></i> - As a <b>Student</b> you can take online exams anytime anywhere effortlessly.</p>
          <hr class="my-4">
          <a class="btn btn-primary btn-lg" href="{% url 'users:examiner_sign_up' %}" role="button">Examiner</a>
          <a class="btn btn-success btn-lg" href="{% url 'users:student_sign_up' %}" role="button">Student</a>
        </div>
    </div>


{% endblock %}

main_app/templates/main_app/manage_questions.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block title %}
    <title>Manage Exam</title>
{% endblock %}


{% block custom_css %}
    <link rel="stylesheet" href="{% static 'main_app/css/manage_questions.css' %}">
{% endblock %}


{% block logout_in_navbar %}

    {% include 'sign_out_button.html' %}

{% endblock %}


{% block content %}

    <div class="container my_container">
    <div class="row">
        <div class="col">

            <form method="post" action="#">{% csrf_token %}
                <div class="input-group my_input_group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Exam Name : </span>
                    </div>
                    <input type="text" name="examName" value="{{ exam_name }}" class="form-control" disabled/>
                </div>
                <div class="input-group my_input_group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Category : </span>
                    </div>
                    <input type="text" name="examCategory" value="{{ exam_category }}" class="form-control" disabled/>
                </div>

                <span><a href="{% url 'main:all_exams' %}" id="backbtn" class="btn btn-secondary backBtn">Back</a></span>
                <span><a href="#newQcollapse" id="addQuestion" class="btn btn-info addQBtb" data-toggle="collapse">Add Question <i class="fa fa-plus"></i></a></span>
            </form>


            <!-- New Question Collapse -->
            <div class="collapse" id="newQcollapse">
                <div class="card card-body newQuestion_collapse" id="my_card">
                <form method="post" action="{% url 'main:add_question' exam_id %}" autocomplete="off">{% csrf_token %}
                       <div class="input-group newQ_my_input_group_collapsebody">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Question : </span>
                            </div>
                            <textarea id="newQ_body" name="newQ_body" class="form-control" aria-label="With textarea" required></textarea>
                        </div>

                        <div class="input-group my_input_group_collapse">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Option 1 : </span>
                            </div>
                            <input id="newQ_option1" name="newQ_option1" type="text" class="form-control" required/>
                        </div>

                        <div class="input-group my_input_group_collapse">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Option 2 : </span>
                            </div>
                            <input id="newQ_option2" name="newQ_option2" type="text" class="form-control" required/>
                        </div>

                        <div class="input-group my_input_group_collapse">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Option 3 : </span>
                            </div>
                            <input id="newQ_option3" name="newQ_option3" type="text" class="form-control" required/>
                        </div>

                        <div class="input-group my_input_group_collapse">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Option 4 : </span>
                            </div>
                            <input id="newQ_option4" name="newQ_option4" type="text" class="form-control" required/>
                        </div>

                        <div class="input-group my_input_group_collapse">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Correct Answer : </span>
                            </div>
                            <input id="newQ_correctA" name="newQ_correct_ans" type="number" min="1" max="4" class="form-control" required/>
                        </div>

                        <hr>

                        <input type="hidden" id="exam_name_forTheNewQ" name="exam_name_forTheNewQ" value="">
                        <input type="hidden" id="exam_code_forTheNewQ" name="exam_code_forTheNewQ" value="">

                        <input type="button" onclick="addNewQuestion({{exam_id}})" name="add_new_question" class="btn btn-success" value="Add">
                   </form>
                </div>
            </div>

        </div>
    </div>
</div>


<!-- Questions List -->
<div class="container QL_contianer">

        <div class="col">

            <h4 class="QL_header">Questions List</h4>

            <div id="questionsList">

            {% for question in questions %}

              <div id="wholeQuestion-{{ question.id }}">
                <div id="question-{{ question.id }}" class="question" data-toggle="collapse" data-target="#question-{{ question.id }}-collapse">Question {{ forloop.counter }}</div>
                <div class="collapse" id="question-{{ question.id }}-collapse">
                    <div class="card card-body question_collapse">

                        <form method="post" action="{% url 'main:update_question' exam_id question.id %}">{% csrf_token %}

                            <div class="input-group my_input_group_collapse">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">Question : </span>
                                </div>
                                <textarea id="question-{{ question.id }}-body" class="form-control" aria-label="With textarea" >{{ question.body }}</textarea>
                            </div>
                            <div class="input-group my_input_group_collapse">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">Option 1 : </span>
                                </div>
                                <input id="question-{{ question.id }}-option-1" value="{{ question.op1 }}" type="text" class="form-control" />
                            </div>

                            <div class="input-group my_input_group_collapse">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">Option 2 : </span>
                                </div>
                                <input id="question-{{ question.id }}-option-2" value="{{ question.op2 }}" type="text" class="form-control" />
                            </div>

                            <div class="input-group my_input_group_collapse">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">Option 3 : </span>
                                </div>
                                <input id="question-{{ question.id }}-option-3" value="{{ question.op3 }}" type="text" class="form-control" />
                            </div>

                            <div class="input-group my_input_group_collapse">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">Option 4 : </span>
                                </div>
                                <input id="question-{{ question.id }}-option-4" value="{{ question.op4 }}" type="text" class="form-control" />
                            </div>
                            <div class="input-group my_input_group_collapse">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">Correct Answer : </span>
                                </div>
                                <input id="question-{{ question.id }}-correctA" value="{{ question.correct_ans }}" type="number" class="form-control" />
                            </div>
                            <hr>

                            <!-- id="updateQuestion-{{ question.id }}-Btn" -->
                            <button id="updateQuestion-{{ question.id }}-Btn" onclick="update_question( {{exam_id}}, {{question.id}} )" class="btn btn-primary updateQ_btn" disabled>Save <i class="far fa-save"></i></button>
                            <a href="#" onclick="delete_question( {{exam_id}}, {{question.id}}, {{ forloop.counter }} )" class="btn btn-danger">Delete <i class="far fa-trash-alt"></i></a>
                        </form>


                     </div>
                  </div>

                </div>

            {% endfor %}

            </div>

        </div>

</div>


{% endblock %}

{% block custom_js %}
    <script src="{% static 'main_app/js/manage_questions.js' %}"></script>
{% endblock %}