bipsu_online_exam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('users/', include('users.urls'))
]

main_app/urls.py
from django.urls import path

from . import views as users_views

app_name = "main"
urlpatterns = [
    path('', users_views.home, name="home"),
    path('add_exam/', users_views.add_exam, name='add_exam'),
    path('all_exams/', users_views.all_exams, name='all_exams'),
    path('delete_exam/<int:exam_id>/', users_views.delete_exam, name='delete_exam'),

    path('manage_exam/<int:exam_id>/add_question/', users_views.add_question, name='add_question'),
    path('manage_exam/<int:exam_id>/edit_exam/', users_views.edit_exam, name='edit_exam'),
    path('manage_exam/<int:exam_id>/show_exam/', users_views.show_exam, name='show_exam'),
    path('manage_exam/<int:exam_id>/do_edit_exam/', users_views.do_edit_exam, name='do_edit_exam'),

    path('manage_exam/<int:exam_id>/manage_questions/', users_views.manage_questions, name='manage_questions'),

    path('do_exam/<int:exam_id>/', users_views.do_exam, name='do_exam'),
    path('update_question/<int:exam_id>/<int:question_id>/', users_views.update_question, name='update_question'),
    path('delete_question/<int:exam_id>/<int:question_id>/', users_views.delete_question, name='delete_question'),
    path('delete_exam/<int:exam_id>/', users_views.delete_exam, name='delete_exam'),
    path('submit_exam/', users_views.submit_exam, name='submit_exam'),
    path('students_scores/', users_views.students_scores, name='students_scores'),

    path('clear_scores/', users_views.clear_scores, name='clear_scores'),

    path('publish_exam/<int:exam_id>/', users_views.publish_exam, name='publish_exam'),
    path('un_publish_exam/<int:exam_id>/', users_views.un_publish_exam, name='un_publish_exam')
]

users/urls.py
from django.urls import path
from . import views as users_views


app_name = "users"
urlpatterns = [

    path('', users_views.home, name='home'),

    path('examiners/sign_up/', users_views.examiner_sign_up, name='examiner_sign_up'),
    path('students/sign_up/', users_views.student_sign_up, name='student_sign_up'),

    path('login/', users_views.the_login, name='login'),

    path('logout/', users_views.the_logout, name='logout'),

    # path('examiners/logout/', users_views.examiner_logout, name='examiner_logout'),
    # path('students/logout/', users_views.student_logout, name='student_logout'),

    path('examiners/<slug>/', users_views.examiner_profile, name='examiner_profile'),
    path('students/<slug>/', users_views.student_profile, name='student_profile'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class MyUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_examiner = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)
    slug = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user)
        super(MyUser, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from users.models import MyUser
from main_app.models import Exam


class MyUserCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(MyUserCreationForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


# class ExaminerCreationForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username', 'password1', 'password2']
#
#
# class StudentCreationForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username', 'first_name', 'last_name', 'password1', 'password2']
#
#
# class ExaminerLoginForm(forms.Form):
#     username = forms.CharField(max_length=128)
#     password = forms.CharField(max_length=128)

users/views.py
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm
from .forms import MyUserCreationForm
from .models import MyUser
from main_app.models import Exam
from django.shortcuts import get_object_or_404
from django.contrib import messages


def home(request):
    my_user = MyUser.objects.get(user=request.user)
    if my_user.is_examiner:
        return HttpResponseRedirect("/users/examiners/" + my_user.slug + "/")
    elif my_user.is_student:
        return HttpResponseRedirect("/users/students/" + my_user.slug + "/")


def examiner_sign_up(request):

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            MyUser.objects.get_or_create(user=user, is_examiner=True)

            messages.success(request, f"Your account created successfully")
            return redirect('users:login')

    else:
        form = MyUserCreationForm()

    data = {
        'form': form
    }
    return render(request, 'users/examiners/examiner_sign_up.html', data)


def student_sign_up(request):
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            MyUser.objects.get_or_create(user=user, is_student=True)

            messages.success(request, f"Your account created successfully")
            return redirect('users:login')

    else:
        form = MyUserCreationForm()

    data = {
        'form': form
    }
    return render(request, 'users/students/student_sign_up.html', data)


# the reason behind using the name 'the_login' , 'the_logout' , is to not conflict with the built in login function
def the_login(request):

    form = AuthenticationForm()

    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f"Welcome ( {username} )")
            return redirect('users:home')

        else:
            messages.error(request, f"Invalid Username or Password !!")

    data = {
        'form': form
    }
    return render(request, 'users/login.html', data)


def the_logout(request):
    logout(request)
    messages.success(request, 'Logged out successfully')
    return redirect('main:home')


def examiner_profile(request, slug):

    if request.method == 'POST':
        profile = get_object_or_404(MyUser, slug=slug)

        if profile.is_valid():
            redirect('users/examiners/examiner_profile.html')

    else:
        profile = AuthenticationForm()

    profile = get_object_or_404(MyUser, slug=slug)
    data = {
        'profile': profile
    }
    return render(request, 'users/examiners/examiner_profile.html', data)


def student_profile(request, slug):

    if request.method == 'POST':
        profile = get_object_or_404(MyUser, slug=slug)

        if profile.is_valid():
            redirect('users/students/student_profile.html')

    else:
        profile = AuthenticationForm()

    profile = get_object_or_404(MyUser, slug=slug)

    exams = Exam.objects.filter(is_published=True)

    data = {
        'profile': profile,
        'exams': exams
    }
    return render(request, 'users/students/student_profile.html', data)

users/templates/users/students/student_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    <title>Profile</title>
{% endblock %}


{% block custom_css %}
    <link rel="stylesheet" href="{% static 'users/students/css/student_profile.css' %}">
{% endblock %}


{% block logout_in_navbar %}

    {% include 'sign_out_button.html' %}

{% endblock %}


{% block content %}

    <div class="container">

        <h1 class="display-4">Welcome <b>{{ profile.user.username }}</b>,</h1>

        <div class="jumbotron">
            <div class="card card-body">

                <!-- Button trigger modal -->
                <div class="top">

                    <h3 class="top_statement">Select an Exam and GO !</h3>

                    <button type="button" class="btn btn-primary startExamBtn" data-toggle="modal" data-target="#exampleModalCenter">
                      Select Exam
                    </button>
                </div>

<!--              <input id="submit" type="submit" name="createExamBtn" class="btn btn-primary btn-lg startExamBtn" value="Start Exam">-->
            </div>
        </div>

    </div>






    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">All Exams</h5>

          </div>
          <div class="modal-body">



              <table class="table" style="text-align: center">
                    {% if exams %}
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Exam Name</th>
                            <th>Category</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody id="table_body">
                        {% for exam in exams %}
                        <tr>
                            <td class="examsCounter">{{ forloop.counter }}</td>
                            <td>{{ exam.exam_name }}</td>
                            <td>{{ exam.category }}</td>
                            <td>
                                <form method="post" action="{% url 'main:do_exam' exam.id %}">{% csrf_token %}
                                    <button type="submit" class="btn btn-outline-primary">Start <i class="far fa-play-circle"></i></button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    {% else %}

                            <h4 class="noExams">No exams found</h4>

                    {% endif %}


                    </tbody>
                </table>



          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>






{% endblock %}

users/templates/users/students/student_sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Sign Up</title>
{% endblock %}

{% block custom_css %}

<style>

  .display-4 {
    font-weight: 500;
    margin: 10px 0;
    font-size: 40px;
  }

  .lead{
    font-weight: 400;
  }

  .jumbotron {
    padding: 15px; background-color: #aaa;
  }
</style>

{% endblock %}

{% block content %}

    <div class="container" style="padding: 10px">

        <h1 class="display-4">Student Sign up</h1>
        <p class="lead">Welcome new comers</p>
        <div class="jumbotron">
            <div class="card card-body">
                <form method="post">{% csrf_token %}
                    {{ form|crispy }}

                    <div style="text-align: right">
                        <a href="{% url 'main:home' %}" style="float: left; margin-right: 5px;" class="btn btn-secondary">Back</a>
                        <button type="submit" style="float: left" class="btn btn-success">Sign up <i class="fa fa-user-plus"></i></button>
                        <span>OR -></span>
                        <a class="btn btn-outline-primary" href="{% url 'users:login' %}">Login</a>
                    </div>
                </form>

            </div>

        </div>
    </div>


{% endblock %}