bipsu_online_exam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('users/', include('users.urls'))
]

users/urls.py
from django.urls import path
from . import views as users_views


app_name = "users"
urlpatterns = [

    path('', users_views.home, name='home'),

    path('examiners/sign_up/', users_views.examiner_sign_up, name='examiner_sign_up'),
    path('students/sign_up/', users_views.student_sign_up, name='student_sign_up'),

    path('login/', users_views.the_login, name='login'),

    path('logout/', users_views.the_logout, name='logout'),

    # path('examiners/logout/', users_views.examiner_logout, name='examiner_logout'),
    # path('students/logout/', users_views.student_logout, name='student_logout'),

    path('examiners/<slug>/', users_views.examiner_profile, name='examiner_profile'),
    path('students/<slug>/', users_views.student_profile, name='student_profile'),

]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Bootstrap-toggle -->
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap2-toggle.min.css" rel="stylesheet">


    <!-- Sweet Alert2 (CDN) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.all.js"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/054a4735f7.js"></script>

    <!-- Custom CSS files -->
    {% block custom_css %}

    {% endblock %}

    {% block title %}<title> </title>{% endblock %}
  </head>
  <body style="background-color: #eee">

    <!-- START navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="border-bottom: 2px solid black;">

          <a class="navbar-brand"><img src="{% static 'main_app/imgs/BIPSU.png' %}" height="40px"></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <a class="nav-link" href="" data-toggle="modal" data-target="#exampleModalScrollable">About</a>
              </li>
            </ul>

            <ul class="navbar-nav ml-auto">
              {% block logout_in_navbar %}
              {% endblock %}
            </ul>
          </div>

        </nav>
    <!-- END navbar -->

    <!-- Navbar Modals -->

    <!-- Button trigger modal -->

    <!-- Button trigger modal -->


      <!-- Modal -->
      <div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalScrollableTitle">About Bipsu Online Exam</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">

              <p>Optimize the students’ experience by reducing the operational risks which exams produce.
                Save time and money in the examination process.</p>

              <br><h6>There are two types of users: Examiners and Students</h6><br>

              <h6><b>The Examiners have the following permissions:</b></h6>
              <ul>
                <li>Adding / Updating / Removing exams.</li>
                <li>Adding / Updating / Removing questions in any exam.</li>
                <li>Previewing the exam before publication.</li>
                <li>Ability to publish and un-publish exams.</li>
                <li>A table contains all created exams to easily access and manage any exam.</li>
                <li>A table contains all students scores in all exams.</li>
                <li>Ability to clear all students scores which allow students to take these exams again.</li>
              </ul>

              <h6><b>The Students can take infinite number of exams.</b></h6>
              <p>Note: It is forbidden for the student to take the same exam twice !</p>


            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
            </div>
          </div>
        </div>
      </div>
    


    <!-- End Navbar Modals -->





    {% block content %}


    {% endblock %}

    <!-- Footer -->

    <footer style="width:100%; position:fixed; left:0px; bottom:-15px; padding-bottom: 5px;">
      <div class="footer-copyright text-center py-3"></div>
    </footer>

    {% if messages %}
        {% for message in messages %}

            <script>
              var msg_type = "{{ message.tags }}";

              if(msg_type == "success"){
                  Swal.fire({
                    type: '{{ message.tags }}',
                    title: 'OK',
                    text: '{{ message }}',
                    showConfirmButton: false,
                    timer: 2000
                  })

              }else if (msg_type == "error"){
                  Swal.fire({
                    type: '{{ message.tags }}',
                    title: 'Oops ..',
                    text: '{{ message }}',
                    showConfirmButton: true,
                  })
              }
            </script>

        {% endfor %}
    {% endif %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <!--    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>    -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap2-toggle.min.js"></script>

    {% block custom_js %}

    {% endblock %}

  </body>
</html>

templates/sign_out_button.html
<li class="nav-item mr-auto">
    <a class="nav-link" href="{% url 'users:logout' %}">Logout <i class="fa fa-sign-out-alt"></i></a>
</li>